const app=require("express")()
const bodyparser=require("body-parser")
app.use(bodyparser.json())
/*const SampleRoutes=require("./routes/sample")
app.use("/",SampleRoutes)*/
const signup=require("./routes/createUser")
const findAll=require("./routes/findUser")
const findById=require("./routes/findById")
const deleteUser=require("./routes/deleteUser")
const updateUser=require("./routes/updateUser")
app.use("/",signup)
app.use("/",findAll)
app.use("/",findById)
app.use("/",deleteUser)
app.use("/",updateUser)
app.listen(3001,()=>console.log("server started"))